### ISSUE TITLE
fix: Final Revision

### ISSUE THREAD

**Issue by algonacci** [citycode-id/mathcamp2#10]
- Tambahkan instruksi di bagian media web (sepertinya youtube video). Misalnya: "Silahkan buka media video disini untuk mendukung kamu belajar mandiri."
- Perbanyak instruksi dari sisi guru nya
- Tambahkan background atau animasi AOS pada tampilan awal setelah siswa login (cenderung membosankan)
- Untuk tugas kelompok dipindahkan ke halaman sebelumnya (tepat diatas diskusi kelompok, terdapat tugas kelompok)

![image](https://user-images.githubusercontent.com/86970816/160560940-ee479a04-8130-4ef8-8032-f9e1751fd76d.png)

- So far revisi 1-3 ajaa

**Comment by algonacci** [comment]
- [ ] Penambahan instruksi saat penggunaan media belajar untuk siswa
- [ ] Penambahan instruksi pada sisi guru
- [ ] Penambahan animasi AOS atau background pada tampilan awal setelah siswa login
- [ ] Pemindahan tugas kelompok ke halaman diskusi kelompok

**Comment by benben4567** [comment]
Done

**Comment by algonacci** [comment]
- [ ] add background image in all pages

![image](https://user-images.githubusercontent.com/86970816/161887355-369cbd64-82a6-4c95-bc71-529a1fcf2682.png)
